/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        secondary: "#c6c6c7",
        "tertiary-fixed": "#cbe6ff",
        "surface-tint": "#ffb4ac",
        "primary-container": "#e01b24",
        "on-primary-fixed-variant": "#93000e",
        "on-surface-variant": "#e7bdb8",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b4b5b5",
        "inverse-primary": "#c00016",
        "surface-variant": "#353534",
        "on-tertiary-container": "#f3f8ff",
        "primary-fixed": "#ffdad6",
        "on-background": "#e5e2e1",
        "inverse-on-surface": "#313030",
        background: "#131313",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#fff6f5",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#2f3131",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "on-primary-fixed": "#410003",
        "secondary-container": "#454747",
        surface: "#131313",
        "on-primary": "#690007",
        error: "#ffb4ab",
        "outline-variant": "#5d3f3c",
        "on-surface": "#e5e2e1",
        primary: "#ffb4ac",
        outline: "#ad8884",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
